version: '3'

services:
  click-service:
    container_name: click-service
    build:
      context: .
      dockerfile: Click/Dockerfile
    platform: linux/x86_64
    image: docker.io/13640225/click-service:1.0
    ports:
      - 9091:9091