version: '3'

services:
  click-service:
    container_name: click-service
    build:
      dockerfile: Click/Dockerfile
    platform: linux/x86_64
    image: click-service:1.0
    ports:
      - 9091:9091