version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "Login Into Docker Hub"
          command: docker login -u "13640225" -p "Baley2020"
      - run: docker-compose build
      - run: docker-compose push