version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      - run: docker-compose build
      - run: docker-compose push