version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - DockerCredential

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn clean package
      - run:
          name: "What is my username?"
          command: echo $DOCKER_USERNAME
      - run:
          name: "Login Into Docker Hub"
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker-compose build
      - run: docker-compose push