version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn clean package
      - run: docker-compose build
      - run: docker-compose push