version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - DockerCredential

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Jar File By Maven"
          command: mvn clean package
      - run:
          name: "What is my username?"
          command: echo $DOCKER_USERNAME
      - run:
          name: "Login Into Docker Hub"
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: "Build Docker Image"
          command: docker build -t docker.io/13640225/click-service:1.0 ./Click
      - run:
          name: "Push Docker Image"
          command: docker push docker.io/13640225/click-service:1.0